import {
  createToolPolicyStore,
  deleteToolPolicyStore,
  detectSchemaDrift,
  getToolPolicyStore,
  listToolPolicyStores,
  putToolPolicyStoreSchema,
  refreshToolPolicyStoreStatus,
  updateToolPolicyStore,
} from "./stores";
import {
  createToolPolicyFromLibrary,
  createToolPolicyStandalone,
  deleteToolPolicy,
  detectToolPolicyDrift,
  getToolPolicy,
  listToolPolicies,
  updateToolPolicy,
} from "./policies";
import {
  createToolPolicyTemplate,
  deleteToolPolicyTemplate,
  listToolPolicyTemplates,
  listToolSyncBatches,
  listToolSyncEvents,
  syncToolPolicy,
  syncToolStore,
  updateToolPolicyTemplate,
} from "./sync-and-templates";

export const toolPolicyStoresRouter = {
  listToolPolicyStores,
  getToolPolicyStore,
  createToolPolicyStore,
  refreshToolPolicyStoreStatus,
  updateToolPolicyStore,
  deleteToolPolicyStore,
  putToolPolicyStoreSchema,
  detectSchemaDrift,
  listToolPolicies,
  getToolPolicy,
  createToolPolicyStandalone,
  createToolPolicyFromLibrary,
  updateToolPolicy,
  deleteToolPolicy,
  detectToolPolicyDrift,
  syncToolPolicy,
  syncToolStore,
  listToolPolicyTemplates,
  createToolPolicyTemplate,
  updateToolPolicyTemplate,
  deleteToolPolicyTemplate,
  listToolSyncBatches,
  listToolSyncEvents,
};
